# Generated by Django 5.0.6 on 2024-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0002_feedbackdata_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.IntegerField()),
                ('coursename', models.CharField(max_length=20)),
                ('timings', models.CharField(max_length=70)),
                ('startdate', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('coursefee', models.IntegerField()),
                ('trainername', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='feedbackdata',
            old_name='Create_at',
            new_name='create_at',
        ),
    ]
